repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key

  - repo: local
    hooks:
      - id: check-codestyle
        name: check
        language: python
        entry: make check
        additional_dependencies: [packaging]
