services:
  back:
    container_name: todo-back
    build: 
      context: ./backend
      target: local_image
    tty: true
    environment:
      - DB_HOST=db
    env_file:
      - backend/.env
    ports:
      - 8000:8000
    depends_on:
      - db

  front:
    container_name: todo-front
    build: ./frontend
    tty: true
    env_file:
      frontend/.env
    ports:
      - 3000:3000
    depends_on:
      - back

  db:
    container_name: todo-db
    image: postgres:15.2
    env_file:
      - .postgres.env
    volumes:
      - pg_data:/var/lib/postgresql/data:cached

volumes:
  pg_data:
    external: false

