"""

Revision ID: d03b63f2559a
Revises: 4cc7d09d234d
Create Date: 2022-08-08 22:52:05.830692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd03b63f2559a'
down_revision = '4cc7d09d234d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('space', sa.Integer(), nullable=False))
    op.add_column('task', sa.Column('space', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'space')
    op.drop_column('project', 'space')
    # ### end Alembic commands ###
