"""

Revision ID: a6e7c231f6f6
Revises: b06ddc922f0f
Create Date: 2022-08-11 22:40:31.541413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e7c231f6f6'
down_revision = 'b06ddc922f0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('color', sa.String(length=6), nullable=True))
    op.add_column('tag', sa.Column('color', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'color')
    op.drop_column('project', 'color')
    # ### end Alembic commands ###
