"""

Revision ID: edbc5c286acd
Revises: a6e7c231f6f6
Create Date: 2022-08-11 23:20:33.688936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edbc5c286acd'
down_revision = 'a6e7c231f6f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('decisive', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'decisive')
    # ### end Alembic commands ###
