"""

Revision ID: 249bb6aec9bf
Revises: c9bd8576a895
Create Date: 2022-12-04 21:39:11.877998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249bb6aec9bf'
down_revision = 'c9bd8576a895'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goal', 'status',
               existing_type=sa.INTEGER(),
               nullable=False,
               server_default='1')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goal', 'status',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
