"""

Revision ID: 985db696b9a7
Revises: d03b63f2559a
Create Date: 2022-08-09 23:39:22.541773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '985db696b9a7'
down_revision = 'd03b63f2559a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'completed_at')
    # ### end Alembic commands ###
