"""

Revision ID: 09508d06a36f
Revises: 249bb6aec9bf
Create Date: 2022-12-04 22:36:52.608048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09508d06a36f'
down_revision = '249bb6aec9bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('archived_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'archived_at')
    # ### end Alembic commands ###
